/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedFamilyIndexRouteImport } from './routes/_authenticated/family.index'
import { Route as AuthenticatedFamilyMemberIdRouteImport } from './routes/_authenticated/family.$memberId'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market.index'
import { Route as AuthenticatedMarketVendorIdRouteImport } from './routes/_authenticated/market.$vendorId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders.$orderId'
import { Route as AuthenticatedRemindersNewRouteImport } from './routes/_authenticated/reminders.new'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyIndexRoute =
  AuthenticatedFamilyIndexRouteImport.update({
    id: '/family/',
    path: '/family/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyMemberIdRoute =
  AuthenticatedFamilyMemberIdRouteImport.update({
    id: '/family/$memberId',
    path: '/family/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/market/',
    path: '/market/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketVendorIdRoute =
  AuthenticatedMarketVendorIdRouteImport.update({
    id: '/market/$vendorId',
    path: '/market/$vendorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemindersNewRoute =
  AuthenticatedRemindersNewRouteImport.update({
    id: '/reminders/new',
    path: '/reminders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/family/$memberId': typeof AuthenticatedFamilyMemberIdRoute
  '/market/$vendorId': typeof AuthenticatedMarketVendorIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/reminders/new': typeof AuthenticatedRemindersNewRoute
  '/family/': typeof AuthenticatedFamilyIndexRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/family/$memberId': typeof AuthenticatedFamilyMemberIdRoute
  '/market/$vendorId': typeof AuthenticatedMarketVendorIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/reminders/new': typeof AuthenticatedRemindersNewRoute
  '/family': typeof AuthenticatedFamilyIndexRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/_authenticated/family/$memberId': typeof AuthenticatedFamilyMemberIdRoute
  '/_authenticated/market/$vendorId': typeof AuthenticatedMarketVendorIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/reminders/new': typeof AuthenticatedRemindersNewRoute
  '/_authenticated/family/': typeof AuthenticatedFamilyIndexRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/vendor'
    | '/family/$memberId'
    | '/market/$vendorId'
    | '/orders/$orderId'
    | '/reminders/new'
    | '/family/'
    | '/market/'
    | '/api/public/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/vendor'
    | '/family/$memberId'
    | '/market/$vendorId'
    | '/orders/$orderId'
    | '/reminders/new'
    | '/family'
    | '/market'
    | '/api/public/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendar'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/vendor'
    | '/_authenticated/family/$memberId'
    | '/_authenticated/market/$vendorId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/reminders/new'
    | '/_authenticated/family/'
    | '/_authenticated/market/'
    | '/api/public/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/': {
      id: '/_authenticated/family/'
      path: '/family'
      fullPath: '/family/'
      preLoaderRoute: typeof AuthenticatedFamilyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/$memberId': {
      id: '/_authenticated/family/$memberId'
      path: '/family/$memberId'
      fullPath: '/family/$memberId'
      preLoaderRoute: typeof AuthenticatedFamilyMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/$vendorId': {
      id: '/_authenticated/market/$vendorId'
      path: '/market/$vendorId'
      fullPath: '/market/$vendorId'
      preLoaderRoute: typeof AuthenticatedMarketVendorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders/new': {
      id: '/_authenticated/reminders/new'
      path: '/reminders/new'
      fullPath: '/reminders/new'
      preLoaderRoute: typeof AuthenticatedRemindersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
  AuthenticatedFamilyMemberIdRoute: typeof AuthenticatedFamilyMemberIdRoute
  AuthenticatedMarketVendorIdRoute: typeof AuthenticatedMarketVendorIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedRemindersNewRoute: typeof AuthenticatedRemindersNewRoute
  AuthenticatedFamilyIndexRoute: typeof AuthenticatedFamilyIndexRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
  AuthenticatedFamilyMemberIdRoute: AuthenticatedFamilyMemberIdRoute,
  AuthenticatedMarketVendorIdRoute: AuthenticatedMarketVendorIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedRemindersNewRoute: AuthenticatedRemindersNewRoute,
  AuthenticatedFamilyIndexRoute: AuthenticatedFamilyIndexRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
